<#
############################################################
Author:				
Author Git:			
Repository:			
Company:			

Filename:			
Creationdate:		

Notes & Usage:
Automatically generated by PM_SimplePowerShellScriptModule
Plaster template by Philipp Maier (github.com/philmph)
############################################################
#>

$PrivateFunctions = Get-ChildItem -Path '.\Src\Modules\Private' -Filter '*.ps1'
$PublicFunctions = Get-ChildItem -Path '.\Src\Modules\Public' -Filter '*.ps1'

foreach ($Function in ($PrivateFunctions + $PublicFunctions)) {
    Write-Verbose -Message "Importing function $($Function.BaseName)"

    try {
        . $Function.FullName
    }
    catch {
        Write-Error -ErrorRecord $_ -ErrorAction Stop
        # Try normal throw in comparison
    }
}

Export-ModuleMember -Function ($PrivateFunctions.BaseName)